FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY ./src/Patient.Feeder Patient.Feeder/
RUN dotnet publish Patient.Feeder -c release -o out

FROM mcr.microsoft.com/dotnet/runtime:6.0
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT dotnet Patient.Feeder.dll