FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app
COPY ./src/Patient.Api Patient.Api/
COPY ./src/Patient.Application Patient.Application/
COPY ./src/Patient.Core Patient.Core/
COPY ./src/Patient.Infrastructure Patient.Infrastructure/
RUN dotnet publish Patient.Api -c release -o out

FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /app
EXPOSE 80
COPY --from=build /app/out .

RUN apt-get update && apt-get install -y curl

ENTRYPOINT dotnet Patient.Api.dll