version: '3.9'
services:
  feeder:
    image: patient-feeder
    build:
      context: .
      dockerfile: Dockerfile.Feeder
    depends_on:
      - api
    command:
      - '/bin/sh'
      - '-c'
      - '/bin/sleep 3000 && dotnet Patient.Feeder.dll'
  api:
    image: patient-api
    build:
      context: .
      dockerfile: Dockerfile.API
    ports:
      - "5000:80"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
