version: '3.9'
services:
  feeder:
    image: patient-feeder
    build:
      context: .
      dockerfile: Dockerfile.Feeder
    depends_on:
      api:
        condition: service_healthy
        restart: true
  api:
    image: patient-api
    build:
      context: .
      dockerfile: Dockerfile.API
    ports:
      - "5000:80"
    depends_on:
      - mongodb
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:80/healthz" ]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 10s
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
